### ISSUE TITLE
Container won't start: '/docker-entrypoint-initdb.d/': No such file or directory

### ISSUE THREAD

**Issue by MikeRippon** [CircleCI-Public/cimg-mariadb#12]
I've just tried using this image for the first time to get our automated tests running in CircleCI, but the container won't start.

Config:

```
executors:
  tests:
    docker:
      - image: cimg/node:16.13.0
      - image: cimg/mariadb:10.5
        environment:
          MARIADB_ROOT_PASSWORD=asecretpassword
```

Container startup step:

```
2021-12-02 14:12:45+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 10.5.13 started.
2021-12-02 14:12:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-12-02 14:12:45+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 10.5.13 started.
ls: cannot access '/docker-entrypoint-initdb.d/': No such file or directory

Exited with code 2

CircleCI received exit code 2

```

I tried the legacy `circleci/mariadb:10.5` and that worked fine

**Comment by BytesGuy** [comment]
@MikeRippon Hi thanks for the report on this. Looks like a line was missed out of the template optimisation. This is now fixed in https://github.com/CircleCI-Public/cimg-mariadb/commit/12f6819865cb0954bc3c8d84c93314350bea927a and https://github.com/CircleCI-Public/cimg-mariadb/commit/466799e9d6c17c15c5f235fc9d681fa85e36f2c2 and the tags have been updated. We are looking at improving testing on the docker images in general to catch these kinds of issues in the future.

**Comment by MikeRippon** [comment]
@BytesGuy that's fixed it thanks!
